clean up test output and add md report
generate xml output and comment from md output

adjust step output capture

capture pytest result?

use the output later

try test again

and again

try a different action

create comment even if tests fail

redirect output again.

ugg

remove colour

remove generate xml message from output, maybe.

different multi line symbole?

return failing exit code from pipe if tests fail

remove header in test output

diff --git a/.github/workflows/run-pytests.yml b/.github/workflows/run-pytests.yml
--- a/.github/workflows/run-pytests.yml
+++ b/.github/workflows/run-pytests.yml
@@ -18,5 +18,33 @@ jobs:
           python -m pip install --upgrade pip
           pip install git+https://github.com/HakaiInstitute/hakai-datasets-repo-standard-tests.git
       - name: Test with pytest
-        run: |
-          pytest --tb=short --pyargs GEM_data_repo_tests
+        id: tests
+        run: >
+          set -o pipefail && pytest --no-header --color=no --tb=no --md-report --junit-xml=test-results.xml --md-report-color=never -r f --pyargs GEM_data_repo_tests | sed 's/^.*generated xml file:.*$//' &> results.md
+      - name: Comment PR with pytest results
+        if: always()
+        uses: thollander/actions-comment-pull-request@v2
+        with:
+          filePath: results.md
+          comment_tag: pytest
+      - name: Surface failing tests
+        if: always()
+        uses: pmeier/pytest-results-action@main
+        with:
+          # A list of JUnit XML files, directories containing the former, and wildcard
+          # patterns to process.
+          # See @actions/glob for supported patterns.
+          path: test-results.xml
+
+          # (Optional) Add a summary of the results at the top of the report
+          summary: true
+
+          # (Optional) Select which results should be included in the report.
+          # Follows the same syntax as `pytest -r`
+          display-options: fEX
+
+          # (Optional) Fail the workflow if no JUnit XML was found.
+          fail-on-empty: true
+
+          # (Optional) Title of the test results section in the workflow summary
+          title: Test results
